# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kalenetwork.org" # the base hostname & protocol for your site
plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag

# SEO settings
title: Kale Network
description: > # this means to ignore newlines until "baseurl:"
  A better blockchain and smart transaction platform which is more decentralized, more efficient, and more secure.
twitter:
  username: kaleCrypto1
  card: summary
# facebook:
#   publisher: https://www.facebook.com/ChiaProject
logo: /img/kale_logo.svg
social:
  links:
    - https://twitter.com/KaleCrypto1
    # - https://www.facebook.com/ChiaProject
    # - https://instagram.com/chia_project
    # - https://www.linkedin.com/company/chia-network/
    - https://github.com/Kale-Network
    # - https://medium.com/@chia.net
    # - https://keybase.io/team/chia_network.public
    - https://discord.com/invite/jEuZsNMD5c
# google_analytics_snippet: |
#   <!-- Global site tag (gtag.js) - Google Analytics -->
#   <script async src="https://www.googletagmanager.com/gtag/js?id=UA-157739092-1"></script>
#   <script>
#     window.dataLayer = window.dataLayer || [];
#     function gtag(){dataLayer.push(arguments);}
#     gtag('js', new Date());

#     gtag('config', 'UA-157739092-1');
#   </script>
defaults:
  - scope:
      path: ""
    values:
      image: https://kalenetwork.org/android-chrome-384x384.png

collections_dir: collections
collections:
  news:
    output: false
  investor_pics:
    output: false
  faq:
    output: false
  job_descriptions:
    output: false

# Build settings
markdown: kramdown
